### ISSUE TITLE
Visualizations sync issues with Internet Explorer

### ISSUE THREAD

**Issue by jonschristensen** [AguaClara/AguaClara.github.io#12]
Antonio noticed this morning that Internet Explorer was having trouble syncing data to display the graph and table. The sync button responded to a click, but then the circle sits there spinning. We tried in Chrome and had no problems, and I was able to replicate the same issue on my machine.

**Comment by ghost** [comment]
Related issue: The webpage for the "tablas" always has the title "Datos sobre la planta de Moroceli" regardless of which plant has been selected in the "ajustes menu". It's not a grave problem, but it is confusing and should be fixed as soon as possible.

**Comment by eak24** [comment]
We're not going to support IE because it is too difficult. Instead we're asking users to install Chrome. see #16
