### ISSUE TITLE
Visualizations table plant name not updating

### ISSUE THREAD

**Issue by jonschristensen** [AguaClara/AguaClara.github.io#14]
I've only confirmed this issue in the browser version, although I think it exists in the app as well. The table page header always displays "Datos Sobre la Planta de Morocelí", even when viewing the data from Otoro - the plant name just needs to be updated according to the plant being viewed.

**Comment by eak24** [comment]
Thanks @jonschristensen! This issue should go in the post.visualizations repo as it is a problem with the app and not the website... when you visit aguaclara.github.io/post.visualizations, you are visiting the visualizations app code, not the website code. Hope that helps clarify! I copied the issue [here. ](https://github.com/AguaClara/post.visualizations/issues/9)
