### ISSUE TITLE
Make app install instruction page

### ISSUE THREAD

**Issue by ghost** [AguaClara/AguaClara.github.io#2]
Make a page that has all the instructions to download both the Collect and the Visualizations app. This should also have a note on updating the apps. This needs to get translated into Spanish. Start by looking [here](https://github.com/AguaClara/POST/wiki/Setting-up-POST-on-ODK-Collect) for a start on the ODK Collect installation instructions. I am not sure how to deal with getting the credentials for submitting data, as we do not want to publish those publicly.

**Comment by eak24** [comment]
Already done.
