### ISSUE TITLE
Integrate sidebar navigation between plants

### ISSUE THREAD

**Issue by jacuerp** [AguaClara/AguaClara.github.io#21]
Remove the settings tab from the navigation and add that functionality to a slide-in navigation menu

**Comment by jacuerp** [comment]
@fawnwong Hey, I just realized there are a bunch of ways this could be organized, all with different trade-offs. 

one option:
>Implementation partner
>>country
>>>region
>>>>city/town/village

Another:
>partner (with host country subtitle)
>>village

another:
>country
>>partner
>>>village

And possibly a few others. What do you think?

**Comment by fawnwong** [comment]
I personally like having the top level being the partner's label, so the first or the second. The second would make more sense at the moment, seeing as we don't have that many plants set up for POST, so making them click through too many drop downs with single options would be a hassle and excessive.

**Comment by eak24** [comment]
I like the idea of as few clicks as possible as well. Keep in mind that we can and should store the particular plant chosen in the computer's browser using the localdata variable plantName. This way they only have to select their plant once! This is already implemented in the website.

**Comment by eak24** [comment]
@fawnwong The current code on the development branch has a few issues:

- some things like plants and plant list are in English. You should either make everything in Spanish OR you should work on localizing the text into both English and Spanish depending on the browser setting. I believe there is an issue to track our website localization progress. If you'd like to look into this, you should put any findings there. 
- In the sidebar under the plantList, the plant names should highlight with a gray overlay like the options above them do. 
- The info box that is blue and informs the user of the specific values on the graph appears in the upper lefthand corner of the page when the page first loads. 

Hope that helps!
