### ISSUE TITLE
Displaying both 1 L/s data and main plant data on same graph

### ISSUE THREAD

**Issue by danelimjoco** [AguaClara/AguaClara.github.io#35]
In order to display both 1 L/s data and main plant data on the same graph, plot.js needs to be changed. In particular, the makeXScale function would need to be changed so that it scales the axis based on the minimum and maximum values in both timeCollected and timeCollected_L. Checkboxes need to be made that allow the user to select what 1 L/s data to display. The drawLines function needs to return x and y based on timeCollected and/or timeCollected_L, depending on which checkboxes are filled. 

@ethan92429 any opinion on whether 1 L/s data and main plant data should be displayable on the same graph or on two separate graphs?

**Comment by eak24** [comment]
@danelimjoco I don't see any reason to. Not that it isn't interesting from an Engineering perspective - just that Engineers can make such a graph with the raw data, while the people using our website probably aren't that interested in inter-plant comparisons. I think in the future there might be some interest in inter-plant comparisons, but for now I think we should leave that to the Engineers with their excel sheets. I might be wrong about this... @ericksonms2 do you see any pressing need to make inter-plant comparisons available on the website?

**Comment by eak24** [comment]
We won't do this. Engineers can download CSV and do it themselves if they like to.
